compile:
		gcc -c ADT_stack.c
		gcc -c ADT_queue.c
		gcc -c main.c
		gcc	-o saq ADT_stack.o ADT_queue.o main.o

all:
		gcc -c ADT_stack.c
		gcc -c ADT_queue.c
		gcc -c main.c
		gcc -o saq ADT_stack.o ADT_queue.o main.o
		./saq

stack:
		gcc -c ADT_stack.c
		gcc -c main.c
		gcc -o ADT_stack ADT_stack.o main.o
		./ADT_stack

