all:
	g++ -o tpu2 CCode.cpp CDecode.cpp CExecute.cpp CRegister.cpp CMemory.cpp main.cpp
	# ./tpu file.bin 20
	# ./tpu file2.bin 108

no4:
	g++ -o tpu2 CCode.cpp CDecode.cpp CExecute.cpp CRegister.cpp CMemory.cpp main.cpp
	./tpu2 file3.bin 15

yes4:
	g++ -o tpu2 CCode.cpp CDecode.cpp CExecute.cpp CRegister.cpp CMemory.cpp main.cpp
	./tpu2 file4.bin 12


